In [37]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
x = np.zeros(10)
print("Original Vector :- ",x)
x[4] = 1
print(" New Vector :-",x)



Original Vector :-  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 New Vector :- [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [38]:
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
y = np.arange(10,50)
print("Created Vector is :-", y)


Created Vector is :- [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [39]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
np.random.randint(0,8,(3,3))


array([[2, 1, 0],
       [3, 2, 4],
       [1, 4, 2]])

In [40]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
arr = np.array([1,2,0,0,4,0])
nzero= arr.nonzero()
print("non-zero elements :-",nzero)


non-zero elements :- (array([0, 1, 4], dtype=int64),)


In [41]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
a = np.random.randint(100,size=(10,10))
print('Original array :-',a)
print('maximum :-',a.max())
print('minimum :-',a.min())

Original array :- [[28 15 66 29 34 83  6 67 74 17]
 [58 98 99 25 47 32 10 14 75 96]
 [17 89 57  1 16  6  7 45 67 86]
 [18 86 57 81 59 34 22 89  2 80]
 [26 61 26 24 32  4 66 33 31  2]
 [40 51 60 33 91 16 19 78 11 73]
 [54 82 69 47 28 69 39 28 71 62]
 [21 15 70 93  2 52 79 64  9 33]
 [13 82 70 97 78 25 70  1 85  3]
 [31 56 39 74 10 64 64 37 83 40]]
maximum :- 99
minimum :- 1


In [36]:
# 6. Create a random vector of size 30 and find the mean value.
import numpy as np

random_vector = np.random.randint(1,50,30)

mean_value = np.mean(random_vector)

print("Random vector  :-", random_vector)
print("Mean value of the vector :-", mean_value)

Random vector  :- [26 39 43 11  3 42 20 33  3 16  6 48 45 20 49  5 40 42 44 40 34 10  2  1
 24 29 41 15  4 19]
Mean value of the vector :- 25.133333333333333
